export const USER_LOGOUT = 'USER/LOGOUT'
export const USER_LOGIN = 'USER/LOGIN'

export const PRODUCT_FETCH_LIST = 'PRODUCT/FETCH/LIST'
export const PRODUCT_FETCH_ONE = 'PRODUCT/FETCH/ONE'
export const PRODUCT_ADD = 'PRODUCT/ADD'
export const PRODUCT_EDIT = 'PRODUCT/EDIT'
export const PRODUCT_REMOVE = 'PRODUCT/REMOVE'

export const APP_ALERT_SHOW = 'APP/ALERT/SHOW'
export const APP_ALERT_HIDE = 'APP/ALERT/HIDE'
export const APP_REDIRECT = 'APP/REDIRECT'
export const APP_REDIRECT_CLEAR = 'APP/REDIRECT/CLEAR'